### ISSUE TITLE
Error while  updating config

### ISSUE THREAD

**Issue by axcl** [gocd-contrib/email-notifier#46] opened 2021-06-04 14:00 UTC
Plugin Version: email-notifier-1.0.0-74.jar
GoCD Version: 21.2.0 

Whenever i tries to change config it throws following error

`Someone has modified the entity. Please update your copy with the changes and try again.`

I have also tried completing removing and adding plugin again but somehow config still stucked.

**Comment by chadlwilson** [comment] 2022-02-14 14:34
Dupe of https://github.com/gocd/gocd/issues/9405

**Closed by chadlwilson** 2022-02-14 14:34 UTC
